name: macOS

# Dependencies of this package
env:
  MACOS_BREW: ${{ 'glib glib-networking gobject-introspection pkg-config jq' }}

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  build-macos:
    strategy:
      matrix:
        os: [macos-13]
    name: macOS version ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Print macOS and Swift version
        run: |
          uname -a
          swift --version

      - name: Fetch macOS dependencies
        run: |
          brew install python@3 || brew link --overwrite python@3
          brew install $MACOS_BREW
          mv /Library/Developer/CommandLineTools /Library/Developer/CommandLineTools.orig || sudo mv /Library/Developer/CommandLineTools /Library/Developer/CommandLineTools.orig

      - name: Checkout SwiftGModule
        uses: actions/checkout@v4
        with:
          path: SwiftGModule

      - name: Build SwiftGModule
        run: |
          cd SwiftGModule
          swift build
          cd ..

      - name: Test SwiftGModule
        run: |
          cd SwiftGModule
          swift test
          cd ..

      - name: Remove unneeded files and archive artefacts
        run: |
          rm -rf _tempGTK
          cd SwiftGModule
          swift package clean
          rm -rf .build/repositories
          cd ..
